blank_issues_enabled: false
contact_links:
  - name: You found an error in the localization?
    url: https://translate.icinga.com/projects/icinga/#search
    about: Please look up the offending source or translation on translate.icinga.com and add a comment (you'll need to sign-in for that) in the respective scope.
