name: Automatic Resolve

on:
  schedule:
    # Every day at UTC+8 midnight
    - cron: "5 8 * * *"
    # Every day at UTC+4 midnight
    - cron: "5 4 * * *"
    # Every day at UTC midnight
    - cron: "5 0 * * *"
    # Every day at UTC-4 midnight
    - cron: "5 20 * * *"
    # Every day at UTC-8 midnight
    - cron: "5 16 * * *"

jobs:
  resolve-conflicts:
    name: Automatic Conflict Resolution
    runs-on: ubuntu-latest
    if: github.repository == 'Icinga/L10n'

    steps:
      - name: Checkout code base
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.ICINGABOT_SSHKEY }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup dependencies
        run: sudo apt-get -y install gettext jq

      - name: Prepare Git environment
        run: |
          git config user.name "icingabot"
          git config user.email "65761963+icingabot@users.noreply.github.com"

      - name: Resolve conflicting pull requests
        run: bin/autoresolve
        env:
          ICINGABOT_TOKEN: "${{ secrets.ICINGABOT_TOKEN }}"
