name: Automatic Merge

on:
  schedule:
    # Every day at midnight
    - cron: "0 0 * * *"

jobs:
  merge:
    name: Automatic pull request merges
    runs-on: ubuntu-latest
    if: github.repository == 'Icinga/L10n'

    steps:
      - name: Merge ready PRs
        uses: pascalgn/automerge-action@135f0bdb927d9807b5446f7ca9ecc2c51de03c4a
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automation"
          MERGE_METHOD: "squash"
          MERGE_DELETE_BRANCH: "true"
