name: Automatic Resolve

on:
  repository_dispatch:
    types:
      - resolve-command

jobs:
  resolve-conflicts:
    name: Automatic Conflict Resolution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code base
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.ICINGABOT_SSHKEY }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup dependencies
        run: sudo apt-get -y install gettext jq

      - name: Prepare Git environment
        run: |
          git config user.name "icingabot"
          git config user.email "65761963+icingabot@users.noreply.github.com"

      - name: Resolve conflicting pull request
        run: bin/autoresolve
        env:
          ICINGABOT_TOKEN: "${{ secrets.ICINGABOT_TOKEN }}"
          PULL_REQUEST_NO: "${{ github.event.client_payload.pull_request.number }}"
