name: Template Update

on:
  repository_dispatch:
    types:
      - update

jobs:
  update:
    name: Gettext template update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code base
        uses: actions/checkout@v4

      - name: Setup dependencies
        run: sudo apt-get -y install gettext

      - name: Dispatch details
        run: echo "${{ github.event.client_payload.origin }} @ ${{ github.event.client_payload.commit }}"

      - name: Update template file
        env:
          ICINGA_GITLAB_CREDENTIAL: ${{ secrets.ICINGA_GITLAB_CREDENTIAL }}
        run: cd ./src/ && ../bin/update

      - name: Open pull request
        uses: peter-evans/create-pull-request@v7
        with:
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: "icinga.pot: Add latest messages"
          title: "Update template file"
          body: "Adds latest messages to the icinga template"
          labels: "automation"
          branch: "update-template-file"
