name: Locale Validation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate:
    name: Locale Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Setup dependencies
        run: sudo apt-get -y install gettext

      - name: Validate locale files
        run: cd ./locale/ && ../bin/validate
